version: '3'

services:
  clickhouse:
    image: "yandex/clickhouse-server:21.3.20.1"
    container_name: "clickhouse"
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    environment:
      CLICKHOUSE_DB: my_db_for_trino
      CLICKHOUSE_USER: clickhouse-user
      CLICKHOUSE_PASSWORD: secret

  coordinator:
    image: "lewuathe/trino-coordinator:354"
    ports:
      - "8080:8080"
    container_name: "coordinator"
    command: http://coordinator:8080 coordinator
    volumes:
      - ./coordinator/etc/catalog:/usr/local/trino/etc/catalog

  worker0:
    image: "lewuathe/trino-worker:354"
    container_name: "worker0"
    ports:
      - "8081:8081"
    command: http://coordinator:8080 worker0
    volumes:
      - ./worker/etc/catalog:/usr/local/trino/etc/catalog

  worker1:
    image: "lewuathe/trino-worker:354"
    container_name: "worker1"
    ports:
      - "8082:8081"
    command: http://coordinator:8080 worker1
    volumes:
      - ./worker/etc/catalog:/usr/local/trino/etc/catalog
